#!/bin/bash
universe = vanilla
log = log/job_$(Cluster)_$(Process).log
error = log/job_$(Cluster)_$(Process).err
executable = cpd.sh
arguments = $(a) $(b)


should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/el8/R413.tar.gz,/home/mzheng54/R_packages.tar.gz,energy_test.R,parameter_cpd.txt,objTest_fctns.R,Sigma_90.Rdata,Sigma_180.Rdata,Sigma_30.Rdata
request_cpus = 1
request_memory = 1GB
request_disk = 0.5GB
max_idle = 5000

queue 1 a,b from parameter_cpd.txt 
